# Generated by Django 5.0.6 on 2024-07-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone_Number', models.CharField(max_length=15)),
                ('Intrument', models.CharField(max_length=50)),
            ],
        ),
    ]
