# Generated by Django 5.0.6 on 2024-07-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraFieldsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(max_length=100)),
                ('integer_field', models.IntegerField()),
                ('date_field', models.DateField()),
                ('datetime_field', models.DateTimeField()),
                ('email_field', models.EmailField(max_length=254)),
                ('boolean_field', models.BooleanField()),
                ('text_field', models.TextField()),
            ],
        ),
    ]
